#!/bin/bash
set -e

# —— 构建 / 签名参数（用环境变量覆盖，不要在仓库里填真实值）——
: "${DEVICE_ID:=00000000-0000000000000000}"                              # 真机 UDID（ios-deploy -i）
: "${TEAM_ID:=YOUR_TEAM_ID}"                                             # Apple Team ID
: "${BUNDLE_ID:=com.example.petfriendly}"                                # 主 App bundle id
: "${CODESIGN_IDENTITY:=Apple Development: you@example.com (YOUR_TEAM_ID)}"
: "${KEYCHAIN_PASSWORD:=}"                                               # 留空则跳过解锁钥匙串

INSTALL_MODE=false
CONFIGURATION="${CONFIGURATION:-Release}"
if [ "$CONFIGURATION" != "Debug" ] && [ "$CONFIGURATION" != "Release" ]; then
  echo "❌ CONFIGURATION 仅支持 Debug 或 Release"
  exit 1
fi

if [ "$1" = "install" ]; then
  INSTALL_MODE=true
  echo "📱 安装模式: 构建完成后将安装到真机设备"
elif [ -n "$1" ]; then
  echo "用法: bash package.sh [install]"
  echo "  (无参数) → 构建 unsigned IPA"
  echo "  install   → 构建 + 签名 + 安装到真机设备"
  exit 1
fi

# 打包前拉取远端最新代码，确保 gitHash 使用最新提交
echo "🔄 正在拉取远端最新代码..."
git pull --ff-only 2>/dev/null || echo "⚠️ git pull 失败（无远程或网络异常），继续使用本地代码"

# 自动生成版本号 (Python)
python3 << 'PYEOF'
import subprocess, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
v = open('VERSION').read().strip()
h = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).decode().strip()
with open('PetFriendly/Utils/Version.generated.swift', 'w') as f:
    f.write('// Generated by package.sh\n')
    f.write('import Foundation\n\n')
    f.write('enum AppVersion {\n')
    f.write(f'    static let gitHash = "{h}"\n')
    f.write(f'    static let version = "{v}"\n')
    f.write('}\n')
print(f'📝 Version: {v}, Hash: {h}')
PYEOF

CURRENT=$(tr -d '[:space:]' < VERSION)
BUILD_NUMBER=$(echo "$CURRENT" | cut -d. -f3)

echo "🚀 开始在本地构建 iOS 项目 (iphoneos, $CONFIGURATION)..."

# 1. 自动注入 Alamofire 的 Info.plist (如果不存在)
ALAMOFIRE_DIR="../Alamofire"
if [ -d "$ALAMOFIRE_DIR" ] && [ ! -f "$ALAMOFIRE_DIR/Info.plist" ]; then
  echo "⚠️ 发现本地 Alamofire 缺失 Info.plist，正在生成..."
  cat <<EOF > "$ALAMOFIRE_DIR/Info.plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleIdentifier</key>
  <string>org.alamofire.Alamofire</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>Alamofire</string>
  <key>CFBundlePackageType</key>
  <string>FMWK</string>
  <key>CFBundleShortVersionString</key>
  <string>1.0</string>
  <key>CFBundleVersion</key>
  <string>1</string>
</dict>
</plist>
EOF
fi

# 2. 清理旧的构建目录
rm -rf dd
echo "✅ 已清理旧的构建缓存"

# 3. 缺少本地配置时自动拷贝模板（Secrets.swift 不入库）
if [ ! -f "PetFriendly/Secrets.swift" ]; then
  echo "⚠️ 未找到 PetFriendly/Secrets.swift，正在从模板生成（请按需填写真实配置）"
  sed 's/SecretsTemplate/Secrets/g' PetFriendly/Secrets.example.swift > PetFriendly/Secrets.swift
fi

# 4. 开始编译
echo "🔨 正在使用 xcodebuild 编译..."

xcodebuild clean build \
  -project PetFriendly.xcodeproj \
  -scheme PetFriendly \
  -sdk iphoneos \
  -configuration "$CONFIGURATION" \
  -derivedDataPath "dd" \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  MARKETING_VERSION="$CURRENT" \
  CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
  ONLY_ACTIVE_ARCH=NO \
  SKIP_WATCH_BUILD=1

# 5. 检查编译结果
APP_PATH="dd/Build/Products/${CONFIGURATION}-iphoneos/PetFriendly.app"
if [ ! -d "$APP_PATH" ]; then
  echo "❌ 编译失败：未找到 .app 包"
  exit 1
fi

# 6. 移除 Watch App（sideload 兼容）
rm -rf "$APP_PATH/Watch"
echo "📱 已确保 Watch App 不在包内"

# 7. 创建 Payload 目录并打包 IPA
echo "📦 正在打包 IPA..."
rm -rf Payload
mkdir Payload
cp -r "$APP_PATH" Payload/
rm -f PetFriendly.ipa
zip -r PetFriendly.ipa Payload/ -x "*.DS_Store"
rm -rf Payload
echo "🎉 打包成功! 文件已生成于: $(pwd)/PetFriendly.ipa"

# 8. 打包成功，自动累加版本号
MAJOR=$(echo "$CURRENT" | cut -d. -f1)
MINOR=$(echo "$CURRENT" | cut -d. -f2)
PATCH=$(echo "$CURRENT" | cut -d. -f3)
NEXT_PATCH=$((PATCH + 1))
echo "$MAJOR.$MINOR.$NEXT_PATCH" > VERSION
echo "📈 版本: $CURRENT → $MAJOR.$MINOR.$NEXT_PATCH"

# 9. 安装模式: 签名 + ios-deploy 安装
if [ "$INSTALL_MODE" = true ]; then
  echo "📱 正在签名并安装到真机设备..."
  # 解锁钥匙串（口令通过 KEYCHAIN_PASSWORD 环境变量注入，留空则跳过）
  if [ -n "$KEYCHAIN_PASSWORD" ]; then
    security unlock-keychain -p "$KEYCHAIN_PASSWORD" ~/Library/Keychains/login.keychain-db 2>/dev/null
  fi
  
  # 解压并签名
  EXTRACT_DIR=$(mktemp -d)
  unzip -q PetFriendly.ipa -d "$EXTRACT_DIR"
  
  cat > "$EXTRACT_DIR/entitlements.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>get-task-allow</key>
    <true/>
    <key>application-identifier</key>
    <string>${TEAM_ID}.${BUNDLE_ID}</string>
    <key>com.apple.developer.team-identifier</key>
    <string>${TEAM_ID}</string>
</dict>
</plist>
PLIST
  
  codesign -f -s "$CODESIGN_IDENTITY" \
    --entitlements "$EXTRACT_DIR/entitlements.plist" \
    --timestamp=none \
    "$EXTRACT_DIR/Payload/PetFriendly.app"
  
  cd "$EXTRACT_DIR"
  zip -qr PetFriendly-signed.ipa Payload/
  
  export PATH="$PATH:$HOME/.local/bin"
  echo "⏳ 正在安装到真机设备 (WiFi)..."
  if ios-deploy --bundle PetFriendly-signed.ipa -i "$DEVICE_ID" --justlaunch 2>&1; then
    echo "✅ 安装完成"
  else
    echo "❌ ios-deploy 安装失败"
    echo "  可能原因:"
    echo "  1. Xcode 未配置 Apple ID → 打开Xcode→Settings→Accounts→登录你的 Apple ID"
    echo "  2. iPhone 未在开发者设备列表中"
    echo "  3. WiFi 连接不稳定（尝试用 USB 数据线直连）"
    echo ""
    echo "📌 已生成签名 IPA: $(pwd)/PetFriendly-signed.ipa"
    echo "   可用 iLoader 手动安装: open /Applications/iloader.app"
  fi
  
  cd - > /dev/null
  rm -rf "$EXTRACT_DIR"
  echo "✅ 安装完成"
fi
