#!/bin/bash
VERSION="$(cat VERSION 2>/dev/null || echo 1.0.0)"
GIT_HASH=

# 更新 Version.generated.swift
cat > PetFriendly/Utils/Version.generated.swift << EOF
// This file is generated by update_build_info.sh. Do not edit.
import Foundation

enum AppVersion {
    static let gitHash = ""
    static let version = ""
}
EOF

# 更新 pbxproj 的 MARKETING_VERSION
sed -i '' "s/MARKETING_VERSION = 1.0;/MARKETING_VERSION = ;/g" PetFriendly.xcodeproj/project.pbxproj

echo "Version updated to  ()"
