#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( dirname "$SCRIPT_DIR" )"
GIT_HASH=$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Priority: VERSION file > APP_VERSION env > git tag
if [ -f "$PROJECT_ROOT/VERSION" ]; then
  VERSION=$(cat "$PROJECT_ROOT/VERSION")
elif [ -n "$APP_VERSION" ]; then
  VERSION="${APP_VERSION#v}"
else
  GIT_TAG=$(git -C "$PROJECT_ROOT" describe --tags --abbrev=0 2>/dev/null)
  VERSION="${GIT_TAG#v}"
fi
[ -z "$VERSION" ] && VERSION="1.0.0"

OUTPUT_FILE="$PROJECT_ROOT/PetFriendly/Utils/Version.generated.swift"
mkdir -p "$(dirname "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" << EOT
// This file is generated by update_build_info.sh. Do not edit.
import Foundation

enum AppVersion {
    static let gitHash = "${GIT_HASH}"
    static let version = "${VERSION}"
}
EOT
echo "Generated Version.generated.swift with version: ${VERSION}, hash: ${GIT_HASH}"
